image: Visual Studio 2017

version: "{build}" #until it gets updated at install
configuration: Debug

environment:
  base_version: 5.0.0
  github_deploy: false 
  is_prerelease: true
  package_version: $(BASE_VERSION)-alpha$(APPVEYOR_BUILD_NUMBER)

build: off
test: off

install:
  - ps: Update-AppveyorBuild -Version "$env:PACKAGE_VERSION"
  - ps: dotnet restore /p:Version="$Env:APPVEYOR_BUILD_VERSION"

build_script:
  - ps: dotnet build -c "$Env:CONFIGURATION" /p:Version="$Env:APPVEYOR_BUILD_VERSION"

test_script:
  - ps: dotnet test -c "$Env:CONFIGURATION" /p:Version="$Env:APPVEYOR_BUILD_VERSION"

artifacts:
  - path: 'FSharp.Interop.Dynamic\**\*.nupkg'

skip_branch_with_pr: true

deploy:
  - provider: NuGet
    server: https://www.myget.org/F/dynamitey-ci/api/v2/package
    api_key:
      secure: yKbBrG0QiTfXUvND1/cMMNHxH1Bgal5g7c0pWGwqvjCtKGTtWkpvE2KlZb6E2ZgB
    skip_symbols: false
    symbol_server: https://www.myget.org/F/dynamitey-ci/symbols/api/v2/package
    artifact: /.*\.nupkg/
    
  - provider: GitHub
    artifact: /.*\.nupkg/           # upload all NuGet packages to release assets
    tag: v$(PACKAGE_VERSION)
    description: 'Release description'
    auth_token: 
      secure: JyJYSgeJYFmkaFy7Gro2dQyv/fqZwz1EzJmp2Nf99H6HUpxNR7ilA/OGPcQk0pA8 #jay's public repo token
    draft: true
    prerelease: $(is_prerelease)
    on:
      github_deploy: true


for:
  - branches:
      only:
        - /deploy-v.*-beta.*/
    environment:
      package_version: $(BASE_VERSION)-beta$(APPVEYOR_BUILD_NUMBER)
      is_prerelease: true
      github_deploy: true
  - branches:
      only:
        - /deploy-v[\d,.]*/
    configuration: Release
    environment:
      package_version: $(BASE_VERSION).$(APPVEYOR_BUILD_NUMBER)
      is_prerelease: false
      github_deploy: true