# Travis-CI Build for dynamitey 
# see travis-ci.org for details

language: csharp
  
matrix:
  include:
    - os: osx
      osx_image: xcode9
      dotnet: 1.1.2
      env: TRGTTEST=netcoreapp1.1
    - os: osx
      osx_image: xcode9
      dotnet: 2.0.3
      env: TRGTTEST=netcoreapp2.0
    - os: osx
      osx_image: xcode9
      mono: 5.10.1
      env: TRGTTEST=net46
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 1.1.2
      env: TRGTTEST=netcoreapp1.1
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 2.0.3
      env: TRGTTEST=netcoreapp2.0     
    - os: linux
      dist: trusty
      sudo: required    
      mono: 5.10.1
      env: TRGTTEST=net46
      
solution: FSharp.Interop.Dynamic.sln

install:
  - dotnet restore

script:
  - cd Tests
  - dotnet xunit -framework $TRGTTEST

branches:
  only:
    - master
