# Travis-CI Build for dynamitey 
# see travis-ci.org for details

language: csharp

dotnet:
  - 1.1.2
  - 2.0.3
  - 2.1.0

os:
  - linux
  - osx

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode9
    - dotnet: 1.1.2
      env: TRGTTEST=netcoreapp1.1
    - dotnet: 2.0.3
      env: TRGTTEST=netcoreapp2.0
    - dotnet: 2.1.0
      env: TRGTTEST=net46

      
solution: FSharp.Interop.Dynamic.sln

install:
  - dotnet restore

script:
  - cd Tests
  - dotnet xunit -framework $TRGTTEST

branches:
  only:
    - master
