# Travis-CI Build for dynamitey 
# see travis-ci.org for details

language: csharp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode9
      
solution: FSharp.Interop.Dynamic.sln
    
mono: 5.2.0
dotnet: 2.0.3

install:
  - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/
script:
  - dotnet test

branches:
  only:
    - master
