# Travis-CI Build for dynamitey 
# see travis-ci.org for details

language: csharp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode8.3
      
solution: FSharp.Interop.Dynamic.sln
    
mono: beta
dotnet: 2.0.3

install:
  - msbuild /ver

script:
  - ./build.fsx

branches:
  only:
    - master
