# Travis-CI Build for dynamitey 
# see travis-ci.org for details

language: csharp
solution: FSharp.Interop.Dynamic.sln
env:
  global:
    - EnableNuGetPackageRestore=true
    
mono: latest
dotnet: 1.0.4
dist: trusty

script:
  - ./build.fsx
